addons:
  apt:
    packages:
      - git
      - make
      - curl

install:
  - make init

script:
  - pushd modules/docker
  - make init 
  - make lint
  - popd
  - pushd modules/terraform
  - make init
  - make lint