addons:
  apt:
    packages:
      - git
      - make
      - curl

script:
  - pushd modules/docker
  - make init
  - make lint
  - popd
  - pushd modules/terraform
  - make init
  - make lint
  - popd
  - pushd modules/codepipeline-chatops
  - make init
  - make lint