version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y curl jq unzip wget
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
      - unzip -o terraform.zip -d /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
      - wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.14.11/terragrunt_linux_amd64
      - mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
      - chmod +x /usr/local/bin/terragrunt
      - curl -o /usr/local/bin/slack https://raw.githubusercontent.com/rockymadden/slack-cli/master/src/slack
      - chmod +x /usr/local/bin/slack
  build:
    commands:
      - terraform_environment=$(bash get_terraform_environment.sh)
      - echo "Preparing for $terraform_environment..."
      - echo "Planning shared environment..."
      - cd terraform/shared
      - terragrunt init -input=false
      - terragrunt get --update
      - terragrunt plan -input=false -no-color -out=plan.out
      - terraform show -no-color plan.out > human_output.txt
      - slack file upload human_output.txt $SLACK_CHANNEL --title "[$CODEBUILD_INITIATOR] Shared infrastructure planning"
      - cd ../..
      - echo "Planning $terraform_environment environment..."
      - cd terraform/$terraform_environment
      - terragrunt init -input=false
      - terragrunt get --update
      - terragrunt plan -input=false -no-color -out=plan.out
      - terraform show -no-color plan.out > human_output.txt
      - slack file upload human_output.txt $SLACK_CHANNEL --title "[$CODEBUILD_INITIATOR] $terraform_environment infrastructure planning"
      - cd ../..
artifacts:
  files:
    - '**/*'
