version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y curl jq unzip wget
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
      - unzip -o terraform.zip -d /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
      - wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.16.8/terragrunt_linux_amd64
      - mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
      - chmod +x /usr/local/bin/terragrunt
      - curl -o /usr/local/bin/slack https://raw.githubusercontent.com/rockymadden/slack-cli/master/src/slack
      - chmod +x /usr/local/bin/slack
  build:
    commands:
      - terraform_environment=$(bash get_terraform_environment.sh)
      - echo "Apply for $terraform_environment..."
      - echo "Apply shared environment..."
      - cd terraform/shared
      - terraform apply -no-color -input=false plan.out
      - slack chat send --text "[$CODEBUILD_INITIATOR] Apply was succesful on shared environment" --channel $SLACK_CHANNEL
      - cd ../..
      - echo "Apply $terraform_environment environment..."
      - cd terraform/$terraform_environment
      - terraform apply -no-color -input=false plan.out
      - slack chat send --text "[$CODEBUILD_INITIATOR] Apply was succesful on $terraform_environment environment" --channel $SLACK_CHANNEL
artifacts:
  files:
    - '**/*'
